### ISSUE TITLE
Chocolatey is unable to resolve Chrome's path

### ISSUE THREAD

**Issue by d35ha** [mandiant/VM-Packages#1111]
It seems chocolatey is not able to resolve this path:
 
https://github.com/mandiant/VM-Packages/blob/5efa36041b90a7155ec388e24b3ec7f48eda8c6c/packages/cyberchef.vm/tools/chocolateyinstall.ps1#L28

![cyber_chef](https://github.com/user-attachments/assets/6cd15875-bab4-4461-92e5-dba6afd4aa95)

**Comment by d35ha** [comment]
Fixed at 4951414eb572a735e26694621f29feb9bc513138.

**Comment by Ana06** [comment]
@d35ha I think there is no PR for that change, so this is not fixed. Or am I missing something?

**Comment by emtuls** [comment]
@Ana06 @d35ha 

I believe this issue is related to a Google Chrome installation failure which occurs when Github Actions images are updated to use the latest chrome version (this happens periodically).

When the image that is used by Github Actions updates to use the latest Google Chrome, an error occurs with the `googlechrome.vm` installation because the same version is already installed, thus causing the package to fail to install.

When this package fails to install, it also causes an error for other packages that depend on `googlechrome.vm`, one of those being `cyberchef.vm`. When `googlechrome.vm` is not installed, the path to the browser is not in the location we expect, which also causes a failure for finding the icon in the path we are using.
This particular part of the issue will be resolved when we change the icon for CyberChef to be something other than Google Chrome in this PR: https://github.com/mandiant/VM-Packages/pull/1054

See error below for what I mean by `googlechrome.vm` failing to install in the latest run. The image was recently updated to use the latest chrome browser (https://github.com/actions/runner-images/releases/tag/win22%2F20240912.1) and this issue has been noted in other areas as an issue that can occur: https://github.com/yarnpkg/yarn/issues/1647#issuecomment-339732324
![image](https://github.com/user-attachments/assets/d5870053-e8fb-4921-a591-b7f434231163)

**Comment by Ana06** [comment]
@emtuls the error you mention does not only happen in GH actions, also if you have Chrome already installed. As mentined in https://github.com/mandiant/VM-Packages/issues/1138, we need to add valid exit codes to fix that issue as we do with other installers. But I think the error @d35ha mentions here is different as the package does not fail to install.

**Comment by Ana06** [comment]
I think Chrome and CyberChef are working correctly and that the issue does not happen anymore. Please @d35ha re-open it if it still happens.
